FROM node:24-alpine3.20 AS base

RUN corepack enable && corepack prepare pnpm@9.15.9 --activate

WORKDIR /opt/app

# Install dependencies
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/ui/package.json ./packages/ui/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/
RUN pnpm install --frozen-lockfile

COPY . .

WORKDIR /opt/app/apps/frontend
CMD ["pnpm", "dev"]