FROM golang:1.26-alpine AS base

WORKDIR /opt/app
ENV GOPATH=/opt/app/go \
PATH=$PATH:$GOPATH/bin

RUN apk add --no-cache build-base
RUN go install github.com/air-verse/air@v1.61.7

COPY apps/backend/go.mod apps/backend/go.sum ./
RUN go mod download

COPY apps/backend/ ./

EXPOSE 8080

CMD ["/opt/app/go/bin/air"]
